# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed35c4042c568cbdc3a83a631c04386f12b517409f82be55dde3b4e62eb5088a496a6307fcfb60efb27a5192590bce12fc2cd7a7cf6c6e9ecf5aaece59eb5a4d

test:
  secret_key_base: 0e1c897b7bd698de1c0f866d3bbfc9cc1963d6a79726b44848af8732acc510d92dbc0161d04020e77ad9d754a98199b49ce7face10c257b4a2c304ad1703ca45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
